site_name: TheHive4py Documentation

# mkdocs.yml
site_url: https://thehive-project.github.io/thehive4py
theme:
  name: "material"
  logo: 'images/thehive.png'
  palette:
    primary: 'blue'
    accent: blue

# nav:
#   - Home: index.md
#   - Reference: 
#       Models: reference/models.md
#       Authentication: reference/auth.md
#       API: reference/api.md
#       Query DSL: reference/query.md
#       Exceptions: reference/exceptions.md
#   - Examples:
#       Alert operations: samples/alert-operations.md
#       Case operations: samples/case-operations.md      
#       Task operations: samples/task-operations.md
#       Observable operations: samples/observable-operations.md
#       Admin operations: samples/admin-operations.md
#   - Change log: changelog.md
#   - Code of conduct: code_of_conduct.md

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - awesome-pages

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - thehive4py

extra_css:
  - custom.css

extra:
  social:
    - icon: fontawesome/solid/home
      link: "https://www.thehive-project.org"
    - icon: fontawesome/brands/wordpress
      link: "https://blog.thehive-project.org"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/TheHive_Project"
    - icon: fontawesome/brands/github
      link: "https://github.com/TheHive-Project"
    - icon: fontawesome/brands/gitter
      link: "https://gitter.im/TheHive-Project/TheHive"
repo_name: "TheHive-Project/TheHive4py"
repo_url: "https://github.com/TheHive-Project/TheHive4py"
markdown_extensions:
    - toc:
        permalink: "#"
    - codehilite
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true

